import argparse
import json
import os

from .dolfile import DOLFile
from .symbols import Symbols
from .fingerprint import generate_print, instruction_count
from .demangle import demangle, DemangleStateException

def alkaid_proc(path_to_dol, path_to_symbols, target_name=None, report_json=None):
	f = open(path_to_dol, 'rb')
	dolfile = DOLFile(f)
	f.close()
	f = open(path_to_symbols, 'r')
	symbols = Symbols(f)
	f.close()
	function_names = []
	function_prints = []
	for function_name, address, size in symbols.functions():
		try:
			demangled = demangle(function_name)
			function_name = '::'.join(demangled.classes)+'::'+demangled.function_name
		except DemangleStateException:
			pass
		function = dolfile.read_address(address, size)
		function_print = generate_print(function)
		function_names.append(function_name)
		function_prints.append(function_print)
	if report_json is None:
		for i in range(len(function_names)):
			function_name = function_names[i]
			if target_name is not None and target_name not in function_name:
				continue
			function_print = function_prints[i]
			for j in range(len(function_names)):
				if i == j:
					continue
				new_print = function_prints[j]
				new_name = function_names[j]
				npic = instruction_count(new_print)
				if npic>16 and new_print[4:-4] in function_print and new_print != function_print:
					print(f"[confidence:{npic}] {new_name} is likely inlined in {function_name}")
	else:
		f = open(report_json)
		report = json.load(f)
		f.close()
		for unit in report['units']:
			if 'functions' not in unit:
				continue
			for function in unit['functions']:
				if 'fuzzy_match_percent' not in function:
					continue
				if function['fuzzy_match_percent'] != 100:
					function_name = function['name']
					try:
						demangled = demangle(function_name)
						function_name = '::'.join(demangled.classes)+'::'+demangled.function_name
					except DemangleStateException:
						pass
					if target_name is not None and target_name not in function_name:
						continue
					function_bytes = dolfile.read_address(int(function['metadata']['virtual_address']), int(function['size']))
					function_print = generate_print(function_bytes)
					for i in range(len(function_names)):
						new_print = function_prints[i]
						new_name = function_names[i]
						if function_name == new_name:
							continue
						npic = instruction_count(new_print)
						if npic>16 and new_print[4:-4] in function_print and new_print != function_print:
							print(f"[confidence:{npic}] {new_name} is likely inlined in {function_name}")

def main():
	parser = argparse.ArgumentParser(
		description='Inline function finder',
		formatter_class=argparse.RawTextHelpFormatter
	)
	parser.add_argument(
		'path_to_dol',
		type=str,
		help='Path to the \'main.dol\' file.'
	)
	parser.add_argument(
		'path_to_symbols',
		type=str,
		help='Path to the \'symbols.txt\' file.'
	)
	parser.add_argument(
		'--target-name',
		type=str,
		default=None,
		help='The target function name to search for.'
	)
	parser.add_argument(
		'--report-json',
		type=str,
		default=None,
		help='The report.json file generated by the build process.'
	)
	args = parser.parse_args()
	alkaid_proc(args.path_to_dol, args.path_to_symbols, target_name=args.target_name, report_json=args.report_json)
